# Generated by Django 2.0.2 on 2018-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_Android_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_mate', models.TextField()),
                ('group_name', models.CharField(max_length=20)),
                ('group_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='class_Android_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_password', models.CharField(max_length=20)),
                ('user_friends', models.TextField()),
                ('user_groups', models.TextField()),
                ('user_message_cache', models.TextField()),
                ('user_IP', models.CharField(max_length=10)),
            ],
        ),
    ]
