# Generated by Django 2.0.2 on 2018-02-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Android_respond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_android_user',
            name='user_IP',
            field=models.CharField(max_length=30),
        ),
    ]
