# Generated by Django 2.0.2 on 2018-02-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H5_introduce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_H5_func',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='class_h5_introduce',
            name='J_url',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
